export const DashboardConstant = {
  CONTACT_LIST_SUCCESS: 'CONTACT_LIST_SUCCESS',
  CONTACT_LIST_ERROR: 'CONTACT_LIST_ERROR',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  CHAT_LIST_SUCCESS: 'CHAT_LIST_SUCCESS',
  CHAT_LIST_ERROR: 'CHAT_LIST_ERROR'
}
