export const ContactConstant = {
  CONTACT_CREATE_SUCCESS: 'CONTACT_CREATE_SUCCESS',
  CONTACT_CREATE_ERROR: 'CONTACT_CREATE_ERROR',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  CHAT_LIST_SUCCESS: 'CHAT_LIST_SUCCESS',
  CHAT_LIST_ERROR: 'CHAT_LIST_ERROR'
}
